apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: smart-scrum-poker-prod

resources:
  - config
  - psql-prod-persistent-volume.yaml
  - psql-prod-persistent-volume-claim.yaml
  - ../../templates/app-config/insecure-psql-config
  - ../../templates/app-backend

patches:
  - target: { group: "apps", version: "v1", kind: "Deployment", name: "ssp-backend" }
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: kbalazsworks/smart_scrum_poker_backend_native:commit_sha_short_5322ba9

  - target: { group: "", version: "v1", kind: "Service", name: "ssp-backend" }
    patch: |-
      - op: replace
        path: /spec/ports/0/port
        value: 3013

  - target: { group: "apps", version: "v1", kind: "Deployment", name: "backend-psql" }
    patch: |-
      - op: replace
        path: /spec/template/spec/volumes/0/persistentVolumeClaim/claimName
        value: psql-prod-persistent-volume-claim

  - target: { group: "", version: "v1", kind: "Service", name: "backend-psql-service" }
    patch: |-
      - op: replace
        path: /spec/ports/0/port
        value: 3023

  - target: { group: "networking.k8s.io", version: "v1", kind: "Ingress", name: "ssp-ingress-backend" }
    patch: |-
      - op: replace
        path: /spec/rules/0/http/paths/0/backend/service/port/number
        value: 3013

      - op: replace
        path: /spec/rules/0/host
        value: api.smartscrumpoker.com

      - op: replace
        path: /spec/tls/0/hosts
        value:
          - api.smartscrumpoker.com
