apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: smart-scrum-poker-prod

resources:
  - config
  - ../../templates/app-config/insecure-psql-config
  - ../../templates/app-backend

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: ssp-backend
    patch: |-
      [
        {
          "op": "replace",
          "path": "/spec/template/spec/containers/0/image",
          "value": "kbalazsworks/smart_scrum_poker_backend_native:commit_sha_short_fd81e5b"
        }
      ]

  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: ssp-ingress-backend
    patch: |-
      [
        {
          "op": "replace",
          "path": "/spec/rules/0/http/paths/0/backend/service/port/number",
          "value": 46001
        },
        {
          "op": "replace",
          "path": "/spec/rules/0/host",
          "value": "api.smart-scrum-poker.balazskrizsan.com"
        },
        {
          "op": "replace",
          "path": "/spec/tls/0/hosts",
          "value": ["api.smart-scrum-poker.balazskrizsan.com"]
        }
      ]
