apiVersion: v1
kind: PersistentVolume
metadata:
  name: psql-prod-persistent-volume
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/ssp/prod_psql_data"
