apiVersion: v1
kind: ConfigMap
metadata:
  name: config-files
data:
  logstash.conf: |
    input {
      tcp {
        port => 5044
        codec => json
      }
    }

    output {
      elasticsearch {
        hosts => ["http://elasticsearch:9200"]
      }
    }
