apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: elk-local
spec:
  template:
    spec:
      containers:
        - name: elasticsearch
          env:
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
