apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd
data:
  images: |
    - name: kbalazsworks/smart_scrum_poker_backend_native
      path: spec.template.spec.containers[0].image
      updateStrategy: latest
  log.level: debug
