apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../templates/

namespace: ssp-prod

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: ssp-backend
    patch: |-
      [
        {
          "op": "replace",
          "path": "/spec/template/spec/containers/0/image",
          "value": "kbalazsworks/smart_scrum_poker_backend_native:commit_sha_short_764f243"
        }
      ]

  - target:
      group: apps
      version: v1
      kind: Deployment
      name: ssp-frontend
    patch: |-
      [
        {
          "op": "replace",
          "path": "/spec/template/spec/containers/0/image",
          "value": "kbalazsworks/smart_scrum_poker_frontend:prod_commit_sha_short_8fdc690"
        }
      ]

  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: ssp-ingress-backend
    patch: |-
      [
        {
          "op": "replace",
          "path": "/spec/rules/0/http/paths/0/backend/service/port/number",
          "value": 46001
        },
        {
          "op": "replace",
          "path": "/spec/rules/0/host",
          "value": "api-ssp-prod.balazskrizsan.com"
        },
        {
          "op": "replace",
          "path": "/spec/tls/0/hosts",
          "value": ["api-ssp-prod.balazskrizsan.com"]
        }
      ]

  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: ssp-ingress-frontend
    patch: |-
      [
        {
          "op": "replace",
          "path": "/spec/rules/0/http/paths/0/backend/service/port/number",
          "value": 48010
        },
        {
          "op": "replace",
          "path": "/spec/rules/0/host",
          "value": "ssp-prod.balazskrizsan.com"
        },
        {
          "op": "replace",
          "path": "/spec/tls/0/hosts",
          "value": [ "ssp-prod.balazskrizsan.com" ]
        }
      ]
