apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssp-backend
  labels:
    app: ssp-backend-label
spec:
  replicas: 1
  selector:
    matchLabels:
      service: ssp-backend
  template:
    metadata:
      labels:
        app: ssp-backend-label
        service: ssp-backend
    spec:
      containers:
        - name: ssp-backend
          image: placeholder:placeholder
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
            limits:
              cpu: 400m
              memory: 400Mi
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secrets
          env:
            - name: spring.profiles.active
              value: native
