apiVersion: v1
kind: Service
metadata:
  name: ssp-backend
  labels:
    app: ssp-backend-label
    service: ssp-backend
spec:
  type: NodePort
  selector:
    app: ssp-backend-label
    service: ssp-backend
  ports:
    - name: http
      protocol: TCP
      port: 1111
      targetPort: 8080
