apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-psql
  labels:
    app: backend-psql-label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-psql-label
  template:
    metadata:
      labels:
        app: backend-psql-label
    spec:
      containers:
        - name: postgres
          image: kbalazsworks/extended_psql:0.1
          ports:
            - containerPort: 5432
          imagePullPolicy: IfNotPresent
          lifecycle:
            postStart:
              exec:
                command:
                  - sh
                  - -c
                  - |
                    echo "teszt"
          resources: {}
          envFrom:
            - configMapRef:
                name: insecure-psql-config
            - secretRef:
                name: cloud-secrets
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: postgresql-storage
      volumes:
        - name: postgresql-storage
          persistentVolumeClaim:
            claimName: placeholder-postgresql-persistent-volume-claim
