apiVersion: v1
kind: PersistentVolume
metadata:
  name: psql-uat-persistent-volume
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/ssp/uat_psql_data"
