apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wso2is-psql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wso2is-psql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wso2is-psql
  template:
    metadata:
      labels:
        app: wso2is-psql
    spec:
      containers:
        - name: wso2is-psql
          image: postgres:15
          env:
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: admin
            - name: POSTGRES_DB
              value: admin
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: wso2is-psql-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: wso2is-psql-storage
          persistentVolumeClaim:
            claimName: wso2is-psql-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: wso2is-psql
spec:
  type: LoadBalancer
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: wso2is-psql
