apiVersion: v1
kind: ConfigMap
metadata:
  name: elastalert-config
  namespace: smart-scrum-poker-elk-local-common
data:
  elastalert.yaml: |
    rules_folder: /opt/elastalert/rules
    scan_subdirectories: true
    run_every:
      minutes: 1
    buffer_time:
      minutes: 15
    es_host: elasticsearch
    es_port: 9200
    use_ssl: false
    verify_certs: false
    writeback_index: elastalert
    alert_time_limit:
      days: 2
