apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: ssp-backend
    patch: |-
      [
        {
          "op": "replace",
          "path": "/spec/template/spec/containers/0/image",
          "value": "kbalazsworks/smart_scrum_poker_backend_native:commit_sha_short_fd81e5b"
        }
      ]
