apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: smart-scrum-poker-uat

resources:
  - ../../templates/app-frontend

patches:
  - target: { group: "apps", version: "v1", kind: "Deployment",  name: "ssp-frontend" }
    patch: |-
      - op: "replace"
        path: "/spec/template/spec/containers/0/image"
        value: "kbalazsworks/smart_scrum_poker_frontend:uat_commit_sha_short_0b6e41a"

  - target: { group: "networking.k8s.io", version: "v1", kind: "Ingress", name: "ssp-ingress-frontend" }
    patch: |-
      - op: "replace"
        path: "/spec/rules/0/http/paths/0/backend/service/port/number"
        value: 48010

      - op: "replace"
        path: "/spec/rules/0/host"
        value: "uat.smartscrumpoker.balazskrizsan.com"
