apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ssp--local--grafana-loki-common--app
  namespace: argocd
spec:
  destination:
    namespace: ssp-grafana-local-common
    server: https://kubernetes.default.svc
  project: default
  source:
    path: src/grafana-loki-starter/local-common
    repoURL: https://github.com/balazskrizsan/smart_scrum_poker_argo
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
