apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ssp-local-prod-app
  namespace: argocd
spec:
  destination:
    namespace: smart-scrum-poker-local-prod
    server: https://kubernetes.default.svc
  project: default
  source:
    path: src/ssp-starter/local-prod
    repoURL: https://github.com/balazskrizsan/smart_scrum_poker_argo
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
