apiVersion: v1
kind: ConfigMap
metadata:
  name: namespace-config
  namespace: smart-scrum-poker-uat
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "-1"
data:
  NAMESPACE_NAME: "smart-scrum-poker-uat"
