apiVersion: v1
kind: ConfigMap
metadata:
  name: config-files
  namespace: smart-scrum-poker-elk-common
data:
  logstash.conf: |
    input {
      tcp {
        port => 5044
        codec => json
      }
    }

    filter {
      if [serverEnv] == "PROD" {
        mutate { add_field => { "target_index" => "logs-prod" } }
      } else if [serverEnv] == "UAT" {
        mutate { add_field => { "target_index" => "logs-uat" } }
      } else {
        mutate { add_field => { "target_index" => "logs-fallback" } }
      }
    }

    output {
      elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "%{target_index}"
      }
    }

  logstash.yml: |
    http.host: "0.0.0.0"
    http.port: 9600
    xpack.monitoring.enabled: true
    xpack.monitoring.elasticsearch.hosts: ["http://elasticsearch:9200"]
    log.level: info
    path.logs: /var/log/logstash
