apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: smart-scrum-poker-elk-common
spec:
  template:
    spec:
      containers:
        - name: elasticsearch
          env:
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "512Mi"
