apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: smart-scrum-poker-elk-common
spec:
  template:
    spec:
      containers:
        - name: elasticsearch
          env:
            - name: ES_JAVA_OPTS
              value: "-Xms1g -Xmx1.5g"
          resources:
            requests:
              cpu: "1000m"
              memory: "1Gi"
            limits:
              cpu: "2000m"
              memory: "2Gi"
