apiVersion: v1
kind: ConfigMap
metadata:
  name: elastalert-rules
data:

  elastalert-healthcheck.yaml: |
    name: elastalert_healthcheck
    type: frequency
    index: elastalert-healthcheck
    num_events: 1
    timeframe:
      minutes: 1
    alert:
      - debug

  high-severity-per-second-alert.yaml: |
    name: "High severity per-second alert"
    type: frequency
    index: ssp-*-logs-*
    num_events: 100
    timeframe:
      minutes: 10
    filter:
      - range:
          level_value:
            gt: 30001
    alert: post2
    http_post2_url: "https://api.pushover.net/1/messages.json"
    http_post2_payload:
      token: ${PUSHOVER_TOKEN}
      user: ${PUSHOVER_USER}
      message: "100+ high severity errors detected in the last 10 minutes!"
    realert:
      minutes: 10

  new-poker-started-alert.yaml: |
    name: "New poker started alert"
    type: frequency
    index: ssp-*-logs-long-term
    num_events: 1
    timeframe:
      seconds: 1
    filter:
      - query:
          query_string:
            query: "message:\"New poker started\""
    alert: post2
    http_post2_url: "https://api.pushover.net/1/messages.json"
    http_post2_payload: |
      {
        "token": "${PUSHOVER_TOKEN}",
        "user": "${PUSHOVER_USER}",
        "message": "[{{env}}][{{level}}] New poker game started!"
      }
