apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: smart-scrum-poker-elk-common

resources:
  - config-files.yaml
  - ../base

patches:
  - path: elasticsearch-patch.yaml
  - path: kibana-patch.yaml
  - path: logstash-patch.yaml
