apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: smart-scrum-poker-prod

resources:
  - ../../smart-scrum-poker/prod/cluster-config
  - ../../smart-scrum-poker/prod/jobs
  - ../../smart-scrum-poker/prod/namespace-config
  - ../../smart-scrum-poker/prod/app-backend
  - ../../smart-scrum-poker/prod/app-frontend
