apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ssp-pgadmin-app
  namespace: argocd
spec:
  destination:
    namespace: pgadmin
    server: https://kubernetes.default.svc
  project: default
  source:
    path: src/pgadmin-starter/local
    repoURL: https://github.com/balazskrizsan/smart_scrum_poker_argo
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
