apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: smart-scrum-poker-local-prod

resources:
  - ./config
  - ./../../templates/app-config/insecure-psql-config
  - ./../../templates/app-backend
  - ./../../../ssp-configs/ssp-backend-prod-version

patches:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: ssp-ingress-backend
    patch: |-
      [
        {
          "op": "replace",
          "path": "/spec/rules/0/http/paths/0/backend/service/port/number",
          "value": 46001
        },
        {
          "op": "replace",
          "path": "/spec/rules/0/host",
          "value": "api--smart-scrum-poker.localhost.balazskrizsan.com"
        },
        {
          "op": "replace",
          "path": "/spec/tls/0/hosts",
          "value": ["api--smart-scrum-poker.localhost.balazskrizsan.com"]
        }
      ]
