apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pgadmin

resources:
  - ../../pgadmin

patches:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: pgadmin-ingress
    patch: |-
      - op: add
        path: /spec/tls
        value:
          - hosts:
              - pgadmin.localhost.balazskrizsan.com
            secretName: env-cert

      - op: add
        path: /spec/rules
        value: 
          - host: pgadmin.localhost.balazskrizsan.com
            http:
              paths:
                - backend:
                    service:
                      port:
                        number: 48090
