apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pgadmin

resources:
  - ../../pgadmin

patches:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: pgadmin-ingress
    patch: |-
      - op: add
        path: /spec/tls
        value:
          - hosts:
              - pgadmin.localhost.balazskrizsan.com
            secretName: env-cert

      - op: replace
        path: /spec/rules/0/http/paths/0/backend/service/port/number
        value: 48090

      - op: replace
        path: /spec/rules/0/host
        value: smart-scrum-poker.localhost.balazskrizsan.com
