apiVersion: batch/v1
kind: Job
metadata:
  name: cert-manager-job
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "0"
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: kubectl
          image: adelchouchene/kubectl-curl
          command: ["/bin/sh", "-c"]
          envFrom:
            - secretRef:
                name: cloud-secrets
            - configMapRef:
                name: namespace-config
          args:
            - |
              mkdir /certs

              echo $CERTIFICATE_CRT_PATH
              echo $CERTIFICATE_PRIVATE_KEY_PATH

              curl -o /certs/certificate.crt "$CERTIFICATE_CRT_PATH"
              curl -o /certs/private.key "$CERTIFICATE_PRIVATE_KEY_PATH"

              ls -hal /certs

              kubectl delete secret env-cert -n $NAMESPACE_NAME --ignore-not-found=false
              kubectl create secret tls env-cert \
                -n $NAMESPACE_NAME \
                --key /certs/private.key \
                --cert /certs/certificate.crt
