apiVersion: batch/v1
kind: Job
metadata:
  name: secret-manager-job
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "0"
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: kubectl
          image: kbalazsworks/kubernetes_job_base_image:0.1
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          envFrom:
            - secretRef:
                name: cloud-secrets
            - configMapRef:
                name: namespace-config
          args:
            - |
              echo "$GOOGLE_SERVICE_ACCOUNT" > "/google-service-account.json"
              export GOOGLE_APPLICATION_CREDENTIALS="/google-service-account.json"

              curl -o /secret.enc.yaml "$BACKEND_APP_SECRET_PATH"

              cat <<EOF > /.sops.yaml
              creation_rules:
              - encrypted_regex: '^(data|secrets)$'
                gcp_kms: "projects/smartscrumpoker/locations/global/keyRings/sops/cryptoKeys/sops-key"
              EOF

              sops --verbose --config /.sops.yaml --decrypt /secret.enc.yaml > /secret.yaml

              kubectl delete -f /secret.yaml -n $NAMESPACE_NAME --ignore-not-found=false
              kubectl apply -f /secret.yaml -n $NAMESPACE_NAME
