apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: smart-scrum-poker-elk-local-common

resources:
  - ./config-files.yaml
  - ../templates
  - ./kibana-ingress.yaml

patches:
  - path: elasticsearch-patch.yaml
  - path: kibana-patch.yaml
  - path: logstash-patch.yaml
