apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: smart-scrum-poker-elk-local-common
spec:
  template:
    spec:
      containers:
        - name: logstash
          env:
            - name: LS_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
