apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssp-backend
spec:
  template:
    spec:
      containers:
        - name: ssp-backend
          image: kbalazsworks/smart_scrum_poker_backend_native:commit_sha_short_fd81e5b
